# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'youcodeio' do
      source 'https://github.com/CocoaPods/Specs.git'
      pod 'PromiseKit'
end

target 'youcodeioTests' do

end

target 'youcodeioUITests' do

end
